Library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from . import views
app_name='books'
urlpatterns=[
    path('',views.home,name='home'),
    path('view',views.view_book,name='view'),
    path('add',views.add_book,name='add'),
    path('add2',views.add_book2,name='add2'),
    path('book_detail<int:p>',views.book_detail,name='book_detail'),
    path('book_delete<int:p>',views.book_delete,name='book_delete'),
    path('book_edit<int:p>',views.book_edit,name='book_edit'),
    path('search_view',views.search_view,name='search_view'),
    path('search',views.search,name='search'),
    path('register/',views.register,name='register'),

]

# static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

# Create your models here.


class book(models.Model):
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=30)
    price = models.IntegerField()
    pdf = models.FileField(upload_to='books/pdf')
    cover = models.FileField(upload_to='books/cover', blank=True, null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural='Books'

books/forms.py
from django import forms
from .models import book
class bookForm(forms.ModelForm):
    class Meta:
        model=book
        fields="__all__"

books/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import book
from .forms import bookForm
from django.db.models import Q
from django.contrib.auth.models import User
# Create your views here.


def home(request):
    return render(request, 'index.html')


def view_book(request):
    books = book.objects.all()
    return render(request, 'Bview.html', {'books': books})


def add_book(request):

    return render(request, 'Badd.html')


def add_book2(request):
    if request.method == "POST":
        form = bookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return home(request)
    form = bookForm()
    return render(request, 'add2.html', {'form': form})


def book_detail(request, p):
    b = book.objects.get(id=p)
    return render(request, 'book_detail.html', {'b': b})


def book_delete(request, p):
    b = book.objects.get(id=p)
    b.delete()
    return view_book(request)


def book_edit(request, p):
    b = book.objects.get(id=p)

    # b.delete()
    return render(request, 'Badd.html', {'b': b})


def search_view(request):
    # b=book.objects.get(id=p)
    # b.delete()
    # if request.method=="POST":

    return render(request, 'search.html')


def search(request):
    query = ""
    b = None
    if request.method == "POST":
        query = request.POST['search_for']
        if query:
            b = book.objects.filter(
                Q(title__icontains=query) | Q(author__icontains=query))
        return render(request, 'search.html', {'query': query, 'b': b})
        # b = book.objects.filter(Q(title=request.POST['search_for']) | Q(author=request.POST['search_for']))


def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        password2=request.POST['password2']
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        email=request.POST['email']
        if password==password2:
            u=User.objects.create_user(username=username,password=password,first_name=firstname,last_name=lastname,email=email)
            u.save()
            return redirect('books:home')
        else:
            return HttpResponse('passwords not same')

        

    return render(request, 'register.html')

templates/Badd.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ADD-BOOKS {% endblock %}
{% block content %}
<h2>ADD BOOKS</h2>
<form action="add" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="book_name" placeholder="Book Name" id=""><br>
    <input type="text" name="book_author" placeholder="Book Author" id=""><br>
    <input type="number" name="book_price" placeholder="Book Price" id=""><br>
    pdf file<input type="file" name="pdf"  id=""><br>
    cover img<input type="file" name="cover" id=""><br>
    <input type="submit">
</form>

<center>
    <div>
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
    </div>
</center>


{% endblock %}

templates/Bdel.html
{% extends 'base.html' %}
{% load static %}
{% block title %}DEL-BOOKS {% endblock %}

{% block content %} WHICH BOOK TO BE DELETED {% endblock %}

templates/Bview.html
{% extends 'base.html' %}
{% load static %}
{% block title %}VIEW-BOOKS {% endblock %}

{% block content %}
LIST OF BOOKS

<table border="1" style="border-collapse:collapse;">
    {% for book in books %}
    <tr>
        <th>ID</th>
        <th>Cover</th>
        <th>Name</th>
        <th>Author</th>
        <th>Price</th>
        <th>Pdf</th>
        <th>view</th>
        <th>edit</th>
        <th>Delete</th>
    </tr>
    <tr>
        <td>{{book.id}}</td>
        <td><img height="100px" src="{{book.cover.url}}" alt=""></td>
        <td>{{book.title}}</td>
        <td>{{book.author}}</td>
        <td>{{book.price}}</td>
        <td><a href="{{book.pdf.url}}">Download</a></td>
        <td><a href="{% url 'books:book_detail' book.id %}">view</a></td>

        <td><a href="{% url 'books:book_edit' book.id %}">edit</a></td>
        <td><a href="{% url 'books:book_delete' book.id %}">del</a></td>

    </tr>
    {% endfor %}
</table>



{% endblock %}

templates/add2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ADD-BOOKS 2 {% endblock %}
{% block content %}
<h2>ADD BOOKS 1</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="" id="">
</form>



{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} TITLE {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}VIEW-BOOKS {% endblock %}

{% block content %}

<center>
    id:{{b.id}} <br>
    Name:{{b.title}} <br>
    author:{{b.author}} <br>
    price:{{b.price}} <br>
    <img height="200px" src="{{b.cover.url}}" alt=""><br>
    pdf: <a href="{{b.pdf.url}}">download</a>  <br>

</center>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ADD-BOOKS 2 {% endblock %}
{% block content %}
<h2>edit BOOKS 1</h2>
<!-- <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="" id="">
</form> -->
{% endblock %}

templates/factorial.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ADD-BOOKS 2 {% endblock %}
{% block content %}
<h2>factorial</h2>
<form action="" method="post"> 
    {% csrf_token %}
    {{form}}
    <input type="submit" name="" id=""><br>
    {% if f %}
    <label for="">factorial is :{{f}}</label>
    {% endif %}
</form>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}INDEX{% endblock %}

{% block content %}
<center>
    <h2>LIBRARY</h2>
    <ul>
        <li><a href="/view">VIEW BOOK</a></li>
        <li><a href="/search_view">search BOOK</a></li>
        <li><a href="/add">ADD BOOK</a></li>
        <li><a href="/add2">ADD BOOK2</a></li>
        <li><a href="">factorial</a></li>
        <li><a href="/del">DEL BOOK</a></li>
        <li><a href="/register">register</a></li>
    </ul>
</center>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registraion{% endblock %}
{% block content %}
<h2>Registraion</h2>
<form action="" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username" id="">
    <input type="password" name="password" placeholder="password" id="">
    <input type="password" name="password2" placeholder="confirm password" id="">
    <input type="text" name="first_name" placeholder="First name" id="">
    <input type="text" name="last_name" placeholder="last name" id="">
    <input type="email" name="email" placeholder="email" id="">
    <input type="submit" name="" id="">
</form>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}search-BOOKS 2 {% endblock %}
{% block content %}
<h2>searh BOOKS </h2>
<form action="{% url 'books:search' %}" method="post">
    {% csrf_token %}
    <input type="text" placeholder="search" name="search_for"><br>
    <input type="submit" name="" id="">
</form>
{% if b %}
<table>
    {% for i in b %}
    <tr>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><img src="{{i.cover.url}}" alt="" height="50"></td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}